owners:
  - name: "James"
    projects:
      - name: Covid
        index_patterns:
          - covid-*
  - name: "System"
    projects:
      - name: "System"
        index_patterns:
          - .*


